<?php 
 	/**
	* @property string $id
	* @property string $template
	* @property array $children
	* @property array $data
	* @property string $output
	* @property Loader $load
	* @property ModelAccountActivity $model_account_activity
	* @property ModelAccountAddress $model_account_address
	* @property ModelAccountApi $model_account_api
	* @property ModelAccountCustomField $model_account_custom_field
	* @property ModelAccountCustomer $model_account_customer
	* @property ModelAccountCustomerGroup $model_account_customer_group
	* @property ModelAccountDownload $model_account_download
	* @property ModelAccountNewslettersubscribe $model_account_newslettersubscribe
	* @property ModelAccountOrder $model_account_order
	* @property ModelAccountRecurring $model_account_recurring
	* @property ModelAccountReturn $model_account_return
	* @property ModelAccountReward $model_account_reward
	* @property ModelAccountTransaction $model_account_transaction
	* @property ModelAffiliateActivity $model_affiliate_activity
	* @property ModelAffiliateAffiliate $model_affiliate_affiliate
	* @property ModelAffiliateTransaction $model_affiliate_transaction
	* @property ModelCatalogCatapulta $model_catalog_catapulta
	* @property ModelCatalogCategory $model_catalog_category
	* @property ModelCatalogInformation $model_catalog_information
	* @property ModelCatalogManufacturer $model_catalog_manufacturer
	* @property ModelCatalogOcfilter $model_catalog_ocfilter
	* @property ModelCatalogProduct $model_catalog_product
	* @property ModelCatalogReview $model_catalog_review
	* @property ModelCatalogSmartsearch $model_catalog_smartsearch
	* @property ModelCheckoutComboProducts $model_checkout_combo_products
	* @property ModelCheckoutCoupon $model_checkout_coupon
	* @property ModelCheckoutFraud $model_checkout_fraud
	* @property ModelCheckoutMarketing $model_checkout_marketing
	* @property ModelCheckoutOrder $model_checkout_order
	* @property ModelCheckoutRecurring $model_checkout_recurring
	* @property ModelCheckoutVoucher $model_checkout_voucher
	* @property ModelCheckoutVoucherTheme $model_checkout_voucher_theme
	* @property ModelD_quickcheckoutOrder $model_d_quickcheckout_order
	* @property ModelDesignBanner $model_design_banner
	* @property ModelDesignLayout $model_design_layout
	* @property ModelEcslideshowBanner $model_ecslideshow_banner
	* @property ModelExportYandexMarket $model_export_yandex_market
	* @property ModelExtensionExtension $model_extension_extension
	* @property ModelExtensionModule $model_extension_module
	* @property ModelExtensionNews $model_extension_news
	* @property ModelFeedAnyFeed $model_feed_any_feed
	* @property ModelLocalisationCountry $model_localisation_country
	* @property ModelLocalisationCurrency $model_localisation_currency
	* @property ModelLocalisationLanguage $model_localisation_language
	* @property ModelLocalisationLocation $model_localisation_location
	* @property ModelLocalisationReturnReason $model_localisation_return_reason
	* @property ModelLocalisationShoputilsMailOrderStatus $model_localisation_shoputils_mail_order_status
	* @property ModelLocalisationZone $model_localisation_zone
	* @property ModelModulePpLogin $model_module_pp_login
	* @property ModelModuleShoputilsMailOrderStatus $model_module_shoputils_mail_order_status
	* @property ModelModuleUlogin $model_module_ulogin
	* @property ModelOpenbayAmazonListing $model_openbay_amazon_listing
	* @property ModelOpenbayAmazonOrder $model_openbay_amazon_order
	* @property ModelOpenbayAmazonProduct $model_openbay_amazon_product
	* @property ModelOpenbayAmazonusListing $model_openbay_amazonus_listing
	* @property ModelOpenbayAmazonusOrder $model_openbay_amazonus_order
	* @property ModelOpenbayAmazonusProduct $model_openbay_amazonus_product
	* @property ModelOpenbayEbayOpenbay $model_openbay_ebay_openbay
	* @property ModelOpenbayEbayOrder $model_openbay_ebay_order
	* @property ModelOpenbayEbayProduct $model_openbay_ebay_product
	* @property ModelOpenbayEtsyOrder $model_openbay_etsy_order
	* @property ModelOpenbayEtsyProduct $model_openbay_etsy_product
	* @property ModelPaymentAmazonCheckout $model_payment_amazon_checkout
	* @property ModelPaymentAuthorizenetAim $model_payment_authorizenet_aim
	* @property ModelPaymentAuthorizenetSim $model_payment_authorizenet_sim
	* @property ModelPaymentBankTransfer $model_payment_bank_transfer
	* @property ModelPaymentBluepayHosted $model_payment_bluepay_hosted
	* @property ModelPaymentBluepayRedirect $model_payment_bluepay_redirect
	* @property ModelPaymentCheque $model_payment_cheque
	* @property ModelPaymentCod $model_payment_cod
	* @property ModelPaymentFirstdata $model_payment_firstdata
	* @property ModelPaymentFirstdataRemote $model_payment_firstdata_remote
	* @property ModelPaymentFreeCheckout $model_payment_free_checkout
	* @property ModelPaymentGoogleCheckout $model_payment_google_checkout
	* @property ModelPaymentKaznachey $model_payment_kaznachey
	* @property ModelPaymentKlarnaAccount $model_payment_klarna_account
	* @property ModelPaymentKlarnaInvoice $model_payment_klarna_invoice
	* @property ModelPaymentLiqpay $model_payment_liqpay
	* @property ModelPaymentMoneybookers $model_payment_moneybookers
	* @property ModelPaymentNochex $model_payment_nochex
	* @property ModelPaymentPaymate $model_payment_paymate
	* @property ModelPaymentPaypoint $model_payment_paypoint
	* @property ModelPaymentPayza $model_payment_payza
	* @property ModelPaymentPerpetualPayments $model_payment_perpetual_payments
	* @property ModelPaymentPpExpress $model_payment_pp_express
	* @property ModelPaymentPpPayflow $model_payment_pp_payflow
	* @property ModelPaymentPpPayflowIframe $model_payment_pp_payflow_iframe
	* @property ModelPaymentPpPro $model_payment_pp_pro
	* @property ModelPaymentPpProIframe $model_payment_pp_pro_iframe
	* @property ModelPaymentPpProPf $model_payment_pp_pro_pf
	* @property ModelPaymentPpProUk $model_payment_pp_pro_uk
	* @property ModelPaymentPpStandard $model_payment_pp_standard
	* @property ModelPaymentPrivat24gs $model_payment_privat24gs
	* @property ModelPaymentRealex $model_payment_realex
	* @property ModelPaymentRealexRemote $model_payment_realex_remote
	* @property ModelPaymentSagepay $model_payment_sagepay
	* @property ModelPaymentSagepayDirect $model_payment_sagepay_direct
	* @property ModelPaymentSagepayServer $model_payment_sagepay_server
	* @property ModelPaymentSagepayUs $model_payment_sagepay_us
	* @property ModelPaymentSecuretradingPp $model_payment_securetrading_pp
	* @property ModelPaymentSecuretradingWs $model_payment_securetrading_ws
	* @property ModelPaymentSkrill $model_payment_skrill
	* @property ModelPaymentTwocheckout $model_payment_twocheckout
	* @property ModelPaymentWebPaymentSoftware $model_payment_web_payment_software
	* @property ModelPaymentWorldpay $model_payment_worldpay
	* @property ModelSettingApi $model_setting_api
	* @property ModelSettingExtension $model_setting_extension
	* @property ModelSettingSetting $model_setting_setting
	* @property ModelSettingStore $model_setting_store
	* @property ModelShippingAuspost $model_shipping_auspost
	* @property ModelShippingCitylink $model_shipping_citylink
	* @property ModelShippingFedex $model_shipping_fedex
	* @property ModelShippingFlat $model_shipping_flat
	* @property ModelShippingFree $model_shipping_free
	* @property ModelShippingItem $model_shipping_item
	* @property ModelShippingNewpost2 $model_shipping_newpost2
	* @property ModelShippingParcelforce48 $model_shipping_parcelforce_48
	* @property ModelShippingPickup $model_shipping_pickup
	* @property ModelShippingRoyalMail $model_shipping_royal_mail
	* @property ModelShippingUps $model_shipping_ups
	* @property ModelShippingUsps $model_shipping_usps
	* @property ModelShippingWeight $model_shipping_weight
	* @property ModelToolImage $model_tool_image
	* @property ModelToolOnline $model_tool_online
	* @property ModelToolSimpleRedirectMaster $model_tool_simple_redirect_master
	* @property ModelToolUpload $model_tool_upload
	* @property ModelTotalComboProducts $model_total_combo_products
	* @property ModelTotalCoupon $model_total_coupon
	* @property ModelTotalCredit $model_total_credit
	* @property ModelTotalHandling $model_total_handling
	* @property ModelTotalKlarnaFee $model_total_klarna_fee
	* @property ModelTotalLowOrderFee $model_total_low_order_fee
	* @property ModelTotalReward $model_total_reward
	* @property ModelTotalShipping $model_total_shipping
	* @property ModelTotalSubTotal $model_total_sub_total
	* @property ModelTotalTax $model_total_tax
	* @property ModelTotalTotal $model_total_total
	* @property ModelTotalVoucher $model_total_voucher
	* @property ModelCatalogAttribute $model_catalog_attribute
	* @property ModelCatalogAttributeExt $model_catalog_attribute_ext
	* @property ModelCatalogAttributeGroup $model_catalog_attribute_group
	* @property ModelCatalogAttributeGroupExt $model_catalog_attribute_group_ext
	* @property ModelCatalogCategoryExt $model_catalog_category_ext
	* @property ModelCatalogDownload $model_catalog_download
	* @property ModelCatalogDownloadExt $model_catalog_download_ext
	* @property ModelCatalogFilter $model_catalog_filter
	* @property ModelCatalogFilterExt $model_catalog_filter_ext
	* @property ModelCatalogInformationExt $model_catalog_information_ext
	* @property ModelCatalogManufacturerExt $model_catalog_manufacturer_ext
	* @property ModelCatalogOption $model_catalog_option
	* @property ModelCatalogOptionExt $model_catalog_option_ext
	* @property ModelCatalogProductExt $model_catalog_product_ext
	* @property ModelCatalogRecurring $model_catalog_recurring
	* @property ModelCatalogRecurringExt $model_catalog_recurring_ext
	* @property ModelCatalogReviewExt $model_catalog_review_ext
	* @property ModelCatalogUrlAlias $model_catalog_url_alias
	* @property ModelExtensionEvent $model_extension_event
	* @property ModelExtensionModification $model_extension_modification
	* @property ModelLocalisationGeoZone $model_localisation_geo_zone
	* @property ModelLocalisationLengthClass $model_localisation_length_class
	* @property ModelLocalisationOrderStatus $model_localisation_order_status
	* @property ModelLocalisationReturnAction $model_localisation_return_action
	* @property ModelLocalisationReturnStatus $model_localisation_return_status
	* @property ModelLocalisationStockStatus $model_localisation_stock_status
	* @property ModelLocalisationTaxClass $model_localisation_tax_class
	* @property ModelLocalisationTaxRate $model_localisation_tax_rate
	* @property ModelLocalisationWeightClass $model_localisation_weight_class
	* @property ModelMarketingAffiliate $model_marketing_affiliate
	* @property ModelMarketingAffiliateExt $model_marketing_affiliate_ext
	* @property ModelMarketingCoupon $model_marketing_coupon
	* @property ModelMarketingCouponExt $model_marketing_coupon_ext
	* @property ModelMarketingMarketing $model_marketing_marketing
	* @property ModelMarketingMarketingExt $model_marketing_marketing_ext
	* @property ModelModuleComboproducts $model_module_comboproducts
	* @property ModelModuleDeadcowSeo $model_module_deadcow_seo
	* @property ModelOpenbayAmazon $model_openbay_amazon
	* @property ModelOpenbayAmazonus $model_openbay_amazonus
	* @property ModelOpenbayEbay $model_openbay_ebay
	* @property ModelOpenbayEbayProfile $model_openbay_ebay_profile
	* @property ModelOpenbayEbayTemplate $model_openbay_ebay_template
	* @property ModelOpenbayEtsy $model_openbay_etsy
	* @property ModelOpenbayOpenbay $model_openbay_openbay
	* @property ModelOpenbayOrder $model_openbay_order
	* @property ModelOpenbayVersion $model_openbay_version
	* @property ModelReportActivity $model_report_activity
	* @property ModelReportAffiliate $model_report_affiliate
	* @property ModelReportCoupon $model_report_coupon
	* @property ModelReportCustomer $model_report_customer
	* @property ModelReportMarketing $model_report_marketing
	* @property ModelReportProduct $model_report_product
	* @property ModelReportReturn $model_report_return
	* @property ModelReportSale $model_report_sale
	* @property ModelSaleCustomField $model_sale_custom_field
	* @property ModelSaleCustomer $model_sale_customer
	* @property ModelSaleCustomerBanIp $model_sale_customer_ban_ip
	* @property ModelSaleCustomerExt $model_sale_customer_ext
	* @property ModelSaleCustomerGroup $model_sale_customer_group
	* @property ModelSaleFraud $model_sale_fraud
	* @property ModelSaleNewssubscribers $model_sale_newssubscribers
	* @property ModelSaleOrder $model_sale_order
	* @property ModelSaleRecurring $model_sale_recurring
	* @property ModelSaleReturn $model_sale_return
	* @property ModelSaleReturnExt $model_sale_return_ext
	* @property ModelSaleVoucher $model_sale_voucher
	* @property ModelSaleVoucherExt $model_sale_voucher_ext
	* @property ModelSaleVoucherTheme $model_sale_voucher_theme
	* @property ModelSaleVoucherThemeExt $model_sale_voucher_theme_ext
	* @property ModelSettingNews $model_setting_news
	* @property ModelShoputilsMailOrderStatus $model_shoputils_mail_order_status
	* @property ModelToolBackup $model_tool_backup
	* @property ModelToolExchange1c $model_tool_exchange1c
	* @property ModelToolExportImport $model_tool_export_import
	* @property ModelUserApi $model_user_api
	* @property ModelUserUser $model_user_user
	* @property ModelUserUserGroup $model_user_user_group
	**/
abstract class Controller {
	protected $registry;

	public function __construct($registry) {
		$this->registry = $registry;
	}

	public function __get($key) {
		return $this->registry->get($key);
	}

	public function __set($key, $value) {
		$this->registry->set($key, $value);
	}
}