<?php

class ControllerPricespdfSkatnajaresult extends Controller
{
    public function index()
    {
        require($_SERVER['DOCUMENT_ROOT'] . '/system/library/PDF/TESTPDF.php');
        require($_SERVER['DOCUMENT_ROOT'] . '/system/library/fpdi/fpdi.php');

        $pdf = new FPDI();

        $files = array("gen_prices/skatnaya/bitumlenty.pdf", "gen_prices/skatnaya/vodosyst.pdf", "gen_prices/skatnaya/plenki.pdf",
            "gen_prices/skatnaya/okna.pdf", "gen_prices/skatnaya/membrany.pdf", "gen_prices/skatnaya/soffity.pdf",
            "gen_prices/skatnaya/lestnicy.pdf", "gen_prices/skatnaya/lenty.pdf");
        $pageCount = 0;



        foreach ($files AS $file) {
            // get the page count
            $pageCount = $pdf->setSourceFile($file);
            // iterate through all pages
            for ($pageNo = 1; $pageNo <= $pageCount; $pageNo++) {
                // import a page
                $templateId = $pdf->importPage($pageNo);
                // get the size of the imported page
                $size = $pdf->getTemplateSize($templateId);

                // create a page (landscape or portrait depending on the imported page size)
                if ($size['w'] > $size['h']) {
                    $pdf->AddPage('L', array($size['w'], $size['h']));
                } else {
                    $pdf->AddPage('P', array($size['w'], $size['h']));
                }

                // use the imported page
                $pdf->useTemplate($templateId);

//                $pdf->SetFont('Helvetica');
//                $pdf->SetXY(5, 5);
//                $pdf->Write(8, 'Generated by FPDI');
            }
        }



//        file_put_contents('test.pdf', $pdf->Output());
        $pdf->Output($_SERVER['DOCUMENT_ROOT'] .'prices/skatnajakrovlja.pdf', 'F');
    }
}